In [7]:
import pandas as pd

df = pd.read_csv("cleaned_airbnb_data.csv")
df.head()

,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,revenue,neighbourhood_group_Brooklyn,...,neighbourhood_group_Staten Island,room_type_Private room,room_type_Shared room,availability_category_Medium,availability_category_High,minimum_nights_category_Medium stays,minimum_nights_category_Long stays,reviews_per_month_category_Moderate,reviews_per_month_category_High engagement,log_price
0,40.64749,-73.97237,149,1,9,0.210000,6,365,54385,True,...,False,True,False,False,True,False,False,False,False,5.010635
1,40.75362,-73.98377,225,1,45,0.380000,2,355,79875,False,...,False,False,False,False,True,False,False,False,False,5.420535
2,40.80902,-73.94190,150,3,0,1.373221,1,365,54750,False,...,False,True,False,False,True,False,False,False,False,5.017280
3,40.68514,-73.95976,89,1,270,4.640000,1,194,17266,True,...,False,False,False,True,False,False,False,True,False,4.499810
4,40.79851,-73.94399,80,10,9,0.100000,1,0,0,False,...,False,False,False,False,False,False,True,False,False,4.394449

In [8]:
target = df['log_price']
features = df.drop(['price', 'log_price'], axis=1)

In [9]:
from sklearn.model_selection import train_test_split

features_train, features_test, target_train, target_test = train_test_split(
    features, target, test_size=0.3, random_state=7
)

In [10]:
from sklearn.ensemble import GradientBoostingRegressor

model = GradientBoostingRegressor(n_estimators=200, learning_rate=0.1, random_state=7)
model.fit(features_train, target_train)

predictions = model.predict(features_test)

In [12]:
from sklearn import metrics
import numpy as np

# Since we used log_price as target, convert it back:
actual_values = np.expm1(target_test)
predicted_values = np.expm1(predictions)

print("MAE:", metrics.mean_absolute_error(actual_values, predicted_values))
print("MSE:", metrics.mean_squared_error(actual_values, predicted_values))
print("RMSE:", np.sqrt(metrics.mean_squared_error(actual_values, predicted_values)))
print("R2 Score:", metrics.r2_score(actual_values, predicted_values))

MAE: 28.753846243362155
MSE: 21040.00778574889
RMSE: 145.05174175358562
R2 Score: 0.5265119344134062